version: "3.7"
services:

  ftp-to-s3bucket:
    container_name: ftp-to-s3bucket
    image: ulvestuen/ftp-to-s3bucket:latest
    ports:
      - "2121:2121"
      - "60000-65535:60000-65535"
    environment:
      - FTP_USERNAME=...
      - FTP_PASSWORD=...
      - FTP_IP_ADDRESS=...
      - FTP_PORT=2121
      - S3_BUCKET_NAME=...
      - S3_UPLOAD_INTERVAL=60
      - AWS_REGION=...
      - AWS_ACCESS_KEY_ID=...
      - AWS_SECRET_ACCESS_KEY=...
    volumes:
      - ./files:/src/files